/**
 * Channel automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Channel {
    id?: string
    type?: number
    guild_id?: string
    position?: number
    name?: string
    topic?: string
    nsfw?: boolean
    last_message_id?: string
    bitrate?: number
    user_limit?: number
    rate_limit_per_user?: number
    icon?: string
    owner_id?: string
    application_id?: string
    managed?: boolean
    parent_id?: string
    last_pin_timestamp?: string
    rtc_region?: string
    video_quality_mode?: number
    message_count?: number
    member_count?: number
    default_auto_archive_duration?: number
    permissions?: string
    flags?: number
    total_message_sent?: number
    default_sort_order?: number
    default_forum_layout?: number
}
