"""
ChannelTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen

from channel_message_tag import ChannelMessageTag

class ChannelTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)
    pass

    def message(self) -> ChannelMessageTag:
        return ChannelMessageTag(
            this.http_client,
            this.parser
        )
    pass


