/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {ClientAbstract, CredentialsInterface, TokenStoreInterface} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {ChannelTag} from "./ChannelTag";

export class Client extends ClientAbstract {
    public channel(): ChannelTag
    {
        return new ChannelTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(clientId: string, clientSecret: string, tokenStore: TokenStoreInterface|null, scopes: Array<string>|null): Client
    {
        return new Client('https://discord.com/api/v10', new OAuth2(clientId, clientSecret, 'https://discord.com/api/oauth2/token', 'https://discord.com/oauth2/authorize', tokenStore, scopes));
    }
}
