/**
 * Error automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Error {
    code?: number
    message?: string
    errors?: any
}

