/**
 * MessageAllowedMentions automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface MessageAllowedMentions {
    parse?: Array<string>
    roles?: Array<string>
    users?: Array<string>
    replied_user?: boolean
}

