/**
 * MessageReference automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface MessageReference {
    message_id?: string
    channel_id?: string
    guild_id?: string
    fail_if_not_exists?: boolean
}

