"""
message_embed automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
@dataclass_json
@dataclass
class MessageEmbed:
    title: str
    type: str
    description: str
    url: str
    timestamp: str
    color: int
