"""
message_reference automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
@dataclass_json
@dataclass
class MessageReference:
    message_id: str
    channel_id: str
    guild_id: str
    fail_if_not_exists: bool
