"""
message automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List
from message_embed import MessageEmbed
from message_allowed_mentions import MessageAllowedMentions
@dataclass_json
@dataclass
class Message:
    content: str
    nonce: str
    tts: bool
    embeds: List[MessageEmbed]
    allowed_mentions: MessageAllowedMentions
    message_reference: str
