/**
 * MessageEmbed automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface MessageEmbed {
    title?: string
    type?: string
    description?: string
    url?: string
    timestamp?: string
    color?: number
}
